Verabschiedete Satzung hinzufügen
DE-RSE/satzung pull request #14
Opened 2019-05-22 07:04 UTC by nuest

Siehe #13

2019-05-22 09:02 UTC, sdruskat requested changes
Add links to README, etc.

2019-05-22 09:02 UTC, sdruskat commented on README.md
> +# Satzung von de-RSE e.V.
```

# Satzung des [*de-RSE e.V. - Gesellschaft für Forschungssoftware*](https://de-rse.org)

```

2019-05-22 09:02 UTC, sdruskat commented on README.md
> +Dieses Repository beinhaltet die endgültige Version der Satzung von de-RSE e.V.: `de-RSE-e.V._Satzung_2019-01-07.pdf`.
*des* de-RSE e.V.?

2019-05-22 09:02 UTC, sdruskat commented on README.md
> +Dieses Repository beinhaltet die endgültige Version der Satzung von de-RSE e.V.: `de-RSE-e.V._Satzung_2019-01-07.pdf`.
Und 

```
[` de-RSE-e.V._Satzung_2019-01-07.pdf`](de-RSE-e.V._Satzung_2019-01-07.pdf)
```

2019-05-22 09:02 UTC, sdruskat commented on README.md
> +Die entsprechenden Dateien finden sich im Ordner `Entwurf_und_Recherche`.
```
[`Entwurf_und_Recherche`](Entwurf_und_Recherche/)
```

2019-05-23 06:13 UTC, BFrit commented on README.md
> +# Satzung von de-RSE e.V.
Ok

2019-05-23 06:14 UTC, BFrit commented on README.md
> +Dieses Repository beinhaltet die endgültige Version der Satzung von de-RSE e.V.: `de-RSE-e.V._Satzung_2019-01-07.pdf`.
Finde "des de-RSE e.V." auch besser.

Anmerkung: Solange wir noch die nicht Anerkennung der Gemeinnützigkiet durch haben, besteht die Chance, dass wir nochmals Kleinigkeiten in der Satzung ändern müssen.  Daher kann es sein, dass wir zur finalen Fassung noch eine "finalere" bekommen.

2019-05-23 06:33 UTC, nuest commented on README.md
> +Dieses Repository beinhaltet die endgültige Version der Satzung von de-RSE e.V.: `de-RSE-e.V._Satzung_2019-01-07.pdf`.
Deswegen habe ich das Wort "final" aus dem Dateinamen rausgenommen und es beim Datum belassen.

2019-05-23 06:45 UTC, BFrit reviewed
bin einverstanden

2019-05-23 06:52 UTC, nuest commented
Kümmere mich um die Änderungsvorschläge..

2019-05-23 06:56 UTC, nuest commented on README.md
> +Dieses Repository beinhaltet die endgültige Version der Satzung von de-RSE e.V.: `de-RSE-e.V._Satzung_2019-01-07.pdf`.
Die Links finde ich etwas pingelig :-) Aber gut. Gehen wir mal davon aus, dass viele Leute sich dieses Repo angucken und einen Klick sparen.

2019-05-23 07:01 UTC, nuest commented on README.md
> +# Satzung von de-RSE e.V.
Wenn hier ein "des" ist, dann passt es aber nicht zu "Gesellschaft für Forschungssoftware". Daher habe ich die Überschrift verkürzt (stimmt nun mit dem repo-Namen überein) und den Link in den Text gemacht (keine Dopplung).

2019-05-23 09:37 UTC, sdruskat approved these changes

2019-05-23 09:38 UTC, merged